### ISSUE TITLE
Gride SASS version 

### ISSUE THREAD

**Issue by Lucasktrindade** [guuibayer/gride#12]
I think it's realtivity easy to do sass version, and i can help you to create this version. I need to know if it'll be here, and if you will create a new directory inside doc.

**Comment by guuibayer** [comment]
Nice @Lucasktrindade! You disposes to make a sass or scss version?

**Comment by Lucasktrindade** [comment]
Man i've already done SCSS, you can see in your PR's.

**Comment by guuibayer** [comment]
This implemented in #17, thanks @Lucasktrindade!
