### ISSUE TITLE
Use linter

### ISSUE THREAD

**Issue by thiamsantos** [guuibayer/gride#13]
Will be good to use a linter to enforce a code style in the code. I recommend the [stylint](https://github.com/SimenB/stylint). [Here](https://github.com/thiamsantos/borg-boilerplate/blob/master/.stylintrc) is a example of a configuration file.

**Comment by guuibayer** [comment]
Very good a lint, but you know a lint for stylus and scss? In #12, @Lucasktrindade is willing to help port Gride for scss or sass version, so we can enjoy.

**Comment by thiamsantos** [comment]
I don't know any linter for sass and stylus at the same time. I think that will be necessary add two linters.

**Comment by Lucasktrindade** [comment]
I'm used to use linter at my IDE, but i've seen this node lint https://www.npmjs.com/package/sass-lint

**Comment by guuibayer** [comment]
Yeah, we'll have to put a linter for scss and stylus

**Comment by thiamsantos** [comment]
Working on it right now.

**Comment by thiamsantos** [comment]
Done.

**Comment by thiamsantos** [comment]
The basic rule is that the properties should be alphabetically ordered. And git hooks were added to ensure that everyone follow these rules.
