### ISSUE TITLE
Why the documentation is on a different file?

### ISSUE THREAD

**Issue by thiamsantos** [guuibayer/gride#15]
There are a special why the documentation isn't placed at the readme?

**Comment by guuibayer** [comment]
Nothing in special, but I think the readme would get very big, :grimacing:

**Comment by thiamsantos** [comment]
I think regardless if it were to get too big or not, it's good to put all the documentation of this project in particular at the readme, maybe because most of people will only read the readme, not wanting to go to another file.

>A README is a module consumer's first -- and maybe only -- look into your creation. The consumer wants a module to fulfill their need, so you must explain exactly what need your module fills, and how effectively it does so.
> - [Art of README](https://github.com/noffle/art-of-readme#the-readme-your-one-stop-shop)

**Comment by guuibayer** [comment]
I agree, but I was thinking of creating documentation with this guy, [docsify](https://docsify.js.org), it is based on markdown files.

We can even use the domain, http://gride.info

**Comment by thiamsantos** [comment]
I am satisfied with the answer thanks!
