### ISSUE TITLE
Logo is broken at npm page

### ISSUE THREAD

**Issue by thiamsantos** [guuibayer/gride#16]
![image](https://cloud.githubusercontent.com/assets/13632762/21288267/b915b690-c465-11e6-8117-52674f37d63e.png)

An option will be use the logo from [rawgit](https://rawgit.com/)

**Comment by guuibayer** [comment]
Thanks for the hint, I'll use the [rawgit](https://rawgit.com/).

**Comment by thiamsantos** [comment]
I think that is necessary update the package at npm.
